### ISSUE TITLE
Unexpected results when `:not` is not a pseudo class function

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-selector-not#28]
```css
:not :dir(ltr) {
	color: red;
}
```

becomes :

```css
:not(ltr) {
	color: red;
}
```

expected : 

_as it is invalid_

```css
:not :dir(ltr) {
	color: red;
}
```

It seems as if the plugin just looks for the next bracket pair without considering the actual syntax.

Ideally `postcss-selector-parser` would be used to prevent issues.
